version: '3.8'

services:
  app:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    env_file: .env
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db


  db:
    container_name: db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static:
