version: '3.8'

services:
  # Backend service
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend_network

  # PostgreSQL service
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_network

  # Redis service for caching and task queuing
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend_network

  # Celery worker for background tasks
  backend_celery_worker:
    image: backend  # Использует тот же образ, что и бэкенд
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    networks:
      - backend_network

  # Celery beat for periodic tasks
  backend_celery_beat:
    image: backend  # Использует тот же образ, что и бэкенд
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    networks:
      - backend_network

  # RabbitMQ service for message brokering (future setup)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Интерфейс управления RabbitMQ
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network:
