"""update QuestionsImagesOrm 24

Revision ID: 94992fdcf9d7
Revises: 3769fe64b3ad
Create Date: 2024-12-10 09:49:32.618945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94992fdcf9d7"
down_revision: Union[str, None] = "3769fe64b3ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
