"""update QuestionsImagesOrm 11

Revision ID: b8f5b4c4b28b
Revises: fc9bf4e795f4
Create Date: 2024-12-09 16:50:15.491635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b8f5b4c4b28b"
down_revision: Union[str, None] = "fc9bf4e795f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
