"""update QuestionsImagesOrm 20

Revision ID: 1ac063ca55aa
Revises: 57494a6d125a
Create Date: 2024-12-10 09:39:01.467283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ac063ca55aa"
down_revision: Union[str, None] = "57494a6d125a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
