"""update QuestionsImagesOrm 08

Revision ID: 8b57ec9449d5
Revises: c2fa2b82d750
Create Date: 2024-12-09 16:08:01.029509

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b57ec9449d5"
down_revision: Union[str, None] = "c2fa2b82d750"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
