"""update QuestionsImagesOrm 13

Revision ID: 6d2779d75a7f
Revises: 1d773c516615
Create Date: 2024-12-09 16:53:32.798906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d2779d75a7f"
down_revision: Union[str, None] = "1d773c516615"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
