"""update QuestionsImagesOrm 10

Revision ID: fc9bf4e795f4
Revises: 2c7aad94cba4
Create Date: 2024-12-09 16:48:40.123314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc9bf4e795f4"
down_revision: Union[str, None] = "2c7aad94cba4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
