"""update QuestionsImagesOrm 09

Revision ID: 2c7aad94cba4
Revises: 8b57ec9449d5
Create Date: 2024-12-09 16:08:40.418106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c7aad94cba4"
down_revision: Union[str, None] = "8b57ec9449d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
