"""update QuestionsImagesOrm 23

Revision ID: 3769fe64b3ad
Revises: 1ac063ca55aa
Create Date: 2024-12-10 09:44:29.830146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3769fe64b3ad"
down_revision: Union[str, None] = "1ac063ca55aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
