"""update QuestionsImagesOrm

Revision ID: f879de54e2f7
Revises: 1f62d3b11db1
Create Date: 2024-12-09 15:14:41.240921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f879de54e2f7"
down_revision: Union[str, None] = "1f62d3b11db1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
