"""update QuestionsImagesOrm 15

Revision ID: 1a12a2dc3206
Revises: 55f88adf7d41
Create Date: 2024-12-09 17:27:54.166309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a12a2dc3206"
down_revision: Union[str, None] = "55f88adf7d41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
