"""update QuestionsImagesOrm 12

Revision ID: 1d773c516615
Revises: b8f5b4c4b28b
Create Date: 2024-12-09 16:51:26.046262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d773c516615"
down_revision: Union[str, None] = "b8f5b4c4b28b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
